project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Jiale Zhao"
  site-url: https://jialeuuz.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/jialeuuz/jialeuuz.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#ffffff"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Research Interests"
        href: interests.qmd
      - text: "CV"
        href: cv.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    css: custom.css
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细
